version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/demoApp
permissions:
   - object: /var/www/html/demoApp
     pattern: "**"
     owner: apache
     group: apache
     mode: 777
     type:
       - file

