version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/demoAppAS
permissions:
   - object: /var/www/html/demoAppAS
     pattern: "**"
     owner: www-data
     group: www-data
     mode: 777
     type:
       - file

